### ISSUE TITLE
Missing boost includes in cpp2py (when building triqs doc)

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cpp2py#1]
I am trying to build the Triqs documentation but `c++2rst` breaks due to missing include path to boost.

```
Traceback (most recent call last):
  File "/Users/hugstr/apps/cpp2py/bin/c++2rst", line 36, in <module>
    libclang_location = args.libclang_location
  File "/Users/hugstr/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/cpp2rst.py", line 60, in __init__
    self.root = CL.parse(filename, compiler_options, includes, libclang_location, parse_all_comments)
  File "/Users/hugstr/apps/cpp2py/lib/python2.7/site-packages/cpp2py/clang_parser.py", line 356, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file /Users/hugstr/dev/triqs/triqs/./gfs/../utility/macros.hpp line 25 col 10
'boost/utility/enable_if.hpp' file not found
... Your code must compile before using clang-parser !
make[2]: *** [doc/cpp2rst.log] Error 1
make[2]: *** Deleting file `doc/cpp2rst.log'
make[1]: *** [doc/CMakeFiles/docs_cpp2rst.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I will dig a bit into this. Is `cpp2py` doing boost detection now?

Best, Hugo

**Comment by parcollet** [comment]
Which boost detection ? 
The code must simply be parsed by the compiler.
I guess it is because your boost are in a non standard path, and
the path has not been propagated to the call to c++rst ...
Where is your boost ?

**Comment by HugoStrand** [comment]
I can confirm that `triqs` finds my boost installation

```
-- -------- Boost detection -------------
-- Boost version: 1.59.0
-- Boost include dir: /opt/local/include
-- Boost libraries: 
```
```
/opt/local/include/boost/utility/enable_if.hpp
```
exist on my system

**Comment by HugoStrand** [comment]
@parcollet we need to propagate the whole include environment for `triqs` back to `cpp2py/c++2rst`.

**Comment by HugoStrand** [comment]
The problem is the same for the `mpi` headers. Their path also needs to be propagated back to `c++2rst`.

**Comment by parcollet** [comment]
We will just extract the include property  of the triqs target.

**Comment by HugoStrand** [comment]
I am hitting the same problem in an application (`tprf`) running `c++2rst`.

But when I try to extract the paths from the triqs target I do not get anything. 
```
# get include paths for the triqs target
get_property(TRIQS_INCLUDE_DIRS TARGET triqs PROPERTY INCLUDE_DIRECTORIES)
foreach(I ${TRIQS_INCLUDE_DIRS})
 set (INC  ${INC} -I ${I})
endforeach()

message(STATUS "include paths for c++2rst")
message(STATUS "${INC}")
```
which gives
```
-- include paths for c++2rst
-- 
-- Configuring done
-- Generating done
```
Is the whole triqs target imported by doing `find_package(TRIQS 1.5 EXACT REQUIRED)`? Or do we have to do something else for applications?

**Comment by parcollet** [comment]
Yes the triqs target is imported by the find_package.
but the field is INTERFACE_INCLUDE_DIRECTORIES, not  INCLUDE_DIRECTORIES

**Comment by parcollet** [comment]
@Wentzell : 
We should find a simpler to propagate this to apps. than get_property, foreach, etc...
This should be in the c++2rst target in some way.

**Comment by HugoStrand** [comment]
Ok! I managed to get the includes from `INTERFACE_INCLUDE_DIRECTORIES`. Thanks

**Comment by HugoStrand** [comment]
Here are the current version that works out

```cmake
# ---------------------------------
# Generate C++ doc with c++2rst
# ---------------------------------
# list of namespaces selected by c++2rst
set(NS -N triqs::det_manip -N triqs::mc_tools)

# get include paths for the triqs target
get_property(TRIQS_INCLUDE_DIRS TARGET triqs PROPERTY INTERFACE_INCLUDE_DIRECTORIES)

foreach(I ${TRIQS_INCLUDE_DIRS})
 set (CPP2RST_INCLUDE_DIRS  ${CPP2RST_INCLUDE_DIRS} --includes ${I})
endforeach()

message(STATUS "include paths for c++2rst")
message(STATUS "${CPP2RST_INCLUDE_DIRS}")

add_custom_command(OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/cpp2rst.log DEPENDS triqs 
		   COMMAND c++2rst ${NS} 
		   ${CMAKE_CURRENT_SOURCE_DIR}/reference/doc_root.hpp 
		   --output_directory ${CMAKE_CURRENT_BINARY_DIR}/cpp2rst_generated
		   --includes ${CMAKE_SOURCE_DIR}/ 
		   --includes ${CMAKE_BINARY_DIR}/Config
		   ${CPP2RST_INCLUDE_DIRS}
		   --cxxflags "-std=c++17 -DTRIQS_BUILDING_LIBRARY" 
		   2>&1 > cpp2rst.log
		   VERBATIM) 
add_custom_target(docs_cpp2rst DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/cpp2rst.log) 
add_dependencies(docs_cpp2rst triqs) 
```
