### ISSUE TITLE
c++2py fails with #include<vector> in .hpp file

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/cpp2py#52]
I haven't used cpp2py in a while, but I remember it was working well with std::vector.  Now there seems to be a problem:

c++2py fails as soon as I add ```#include<vector>``` in the .hpp file. This is the example from documentation:

```example.hpp:```

``` c++
#include<vector>

///A wonderful little class
class myclass{
  int a, b;

  public:
    myclass(int a_, int b_) : a(a_), b(b_) {}

    ///getter for member a
    int get_a() const { return a;}
};
```
Then I run the c++2py command and get the following error:
```
jaksa@pv:~/CPP2PY/source/example$ c++2py example.hpp
Welcome to C++2py
Parsing the C++ file (may take a few seconds) ...
... done. 

Analysing dependencies
====================
Error : The following types can not be converted: 

long double (long double)
Traceback (most recent call last):
  File "/home/jaksa/CPP2PY/install/cpp2py/bin/c++2py", line 84, in <module>
    W.generate_desc_file(output_filename = (args.outputname or filename_1) + "_desc.py")
  File "/home/jaksa/CPP2PY/install/cpp2py/lib/python3.10/site-packages/cpp2py/cpp2desc.py", line 288, in generate_desc_file
    import_list, converters_list = self.DE(self.get_all_params_ret_type(param_cls_list), types_being_wrapped_or_converted)
  File "/home/jaksa/CPP2PY/install/cpp2py/lib/python3.10/site-packages/cpp2py/dependency_analyzer.py", line 75, in __call__
    raise TypeError("")
TypeError
```
If I comment out ```#include<vector>``` everything works.

I'm using llvm18.1.6, gcc13.2.0, python 3.10.2, clang module 17.0.6 .

What am I doing wrong?

**Comment by Wentzell** [comment]
Dear @JaksaVucicevic,

Please avoid generating bindings for standard library headers, either by filtering
out a namespace using `-N` or on a per-file basis using `--target_file_only`.

**Comment by JaksaVucicevic** [comment]
This worked, thank you very much!
