### ISSUE TITLE
make fails when #include<array> added to .hpp file

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/cpp2py#53]
When I add ```#include<array>``` to .hpp file, c++2py works, cmake works, but make then fails:

```example.hpp```:
```c++
#include<array>

///A wonderful little class
class myclass{
  int a, b;

  public:
    myclass(int a_, int b_) : a(a_), b(b_) {}

    ///getter for member a
    int get_a() const { return a;}

    //int get_b(std::array<int,3> X) { return X[0]; }
};
```
```
jaksa@pv:~/CPP2PY/source/example$ c++2py example.hpp
Welcome to C++2py
Parsing the C++ file (may take a few seconds) ...
... done. 

Analysing dependencies
Wrapping classes:
    __numeric_traits
    __numeric_traits
    __numeric_traits
    _Iter_less_iter
    _Iter_less_val
    _Val_less_iter
    _Iter_equal_to_iter
    _Iter_equal_to_val
    myclass
Wrapping functions:
    __iter_less_iter
    __iter_less_val
    __iter_comp_val
    __val_less_iter
    __val_comp_iter
    __iter_equal_to_iter
    __iter_equal_to_val
    __iter_comp_val
Generating example_desc.py
```
```
jaksa@pv:~/CPP2PY/build/example$ cmake ../../source/example
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Cpp2PyConfig.cmake with version 2.0.0, hash = a54c23606abe4e19da8f370b9c3faed0fb3ec5ca, root = /home/jaksa/CPP2PY/install/cpp2py
-- Adding cpp2py Python module example
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/jaksa/CPP2PY/build/example
```
```
jaksa@pv:~/CPP2PY/build/example$ make
[ 33%] Generating example_wrap.cxx
Traceback (most recent call last):
  File "/home/jaksa/CPP2PY/source/example//example_desc.py", line 37, in <module>
    module.add_class(c)
  File "/home/jaksa/CPP2PY/install/cpp2py/lib/python3.10/site-packages/cpp2py/wrap_generator.py", line 738, in add_class
    if cls.py_type in self.classes : raise IndexError("The class %s already exists"%cls.py_type)
IndexError: The class NumericTraits already exists
make[2]: *** [CMakeFiles/example.dir/build.make:74: example_wrap.cxx] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
If I exclude ```#include<array>```, everything works, and in the end I am able to load the module in python and use it, just like in the example in the documentation. 

Is it even possible to use std::vector and std::array?

**Comment by Wentzell** [comment]
Dear @JaksaVucicevic,

Please specify a namespace to avoid the generation of for any of the standard library functionality that you are including

**Comment by JaksaVucicevic** [comment]
c++2py -N std
or
c++2py --tareget_file_only
works, thanks!

**Comment by JaksaVucicevic** [comment]
c++2py -N std
or
c++2py --tareget_file_only
works, thanks!
