### ISSUE TITLE
Problem with c++2rst in combination with llvm-5.0

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/cpp2py#9]
Dear @parcollet ,

I am trying to build the unstable branch of cpp2py/triqs/dft_tools/cthyb/... using clang-5.0 and llvm-5.0 but get into trouble when trying to build the autogenerated docs of triqs. `c++2rst` crashes with the following:
```
[ 98%] Generating cpp2rst.log
Traceback (most recent call last):
  File "/Users/hugstr/apps/cpp2py/bin/c++2rst", line 36, in <module>
    libclang_location = args.libclang_location
  File "/Users/hugstr/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/cpp2rst.py", line 60, in __init__
    self.root = CL.parse(filename, compiler_options, includes, libclang_location, parse_all_comments)
  File "/Users/hugstr/apps/cpp2py/lib/python2.7/site-packages/cpp2py/clang_parser.py", line 354, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h line 35 col 5
"Python.h requires that stdio.h define NULL." file /opt/local/libexec/llvm-5.0/include/c++/v1/string.h line 95 col 49
unknown type name 'size_t' file /opt/local/libexec/llvm-5.0/include/c++/v1/string.h line 97 col 46
unknown type name 'size_t' file /opt/local/libexec/llvm-5.0/include/c++/v1/string.h line 99 col 46
unknown type name 'size_t' file /opt/local/libexec/llvm-5.0/include/c++/v1/stdlib.h line 116 col 35
unknown type name 'ldiv_t' file /opt/local/libexec/llvm-5.0/include/c++/v1/stdlib.h line 118 col 34
unknown type name 'lldiv_t' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pyport.h line 159 col 9
unknown type name 'uintptr_t' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h line 307 col 38
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h line 459 col 44
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 12 col 5
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 15 col 20
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 44 col 40
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 45 col 54
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 46 col 1
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 65 col 45
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/fileobject.h line 66 col 49
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pythonrun.h line 35 col 36
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pythonrun.h line 36 col 38
unknown type name 'FILE' file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pythonrun.h line 38 col 41
unknown type name 'FILE' file None line 0 col 0
too many errors emitted, stopping now
... Your code must compile before using clang-parser !
make[2]: *** [doc/cpp2rst.log] Error 1
make[2]: *** Deleting file `doc/cpp2rst.log'
make[1]: *** [doc/CMakeFiles/docs_cpp2rst.dir/all] Error 2
make: *** [all] Error 2
```
it is hard to debug this since the log file is deleted by `cmake`
```
make[2]: *** Deleting file `doc/cpp2rst.log'
```
Please help.

**Comment by HugoStrand** [comment]
@parcollet do you have any ideas on what is going wrong here?

I have to use `clang-5.0` for ctint which (in macports) depends on `llvm-5.0`. In the current state I can not build _any_ documentation... I need the docs especially for debugging the bse in `tprf`.

Best regards,
Hugo

**Comment by Wentzell** [comment]
Closing this as outdated. TPRF Doc builds are currently successful with recent versions of llvm. C.f. jenkins.flatironinstitute.org
